# Generated by Django 2.2.7 on 2021-03-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table1', models.CharField(max_length=500)),
            ],
        ),
    ]
